### ISSUE TITLE
Dataset Download Link Unreachable

### ISSUE THREAD

**Issue by hashshura** [JakubSochor/BrnoCompSpeed#10]
Hello, I am an undergraduate student currently having a similar project regarding speed detection in a traffic video.

It seems that the website https://medusa.fit.vutbr.cz/traffic/research-topics/traffic-camera-calibration/brnocompspeed/ is down at the moment (checked since last month). Does anyone have the access to full or partial mirrors of the dataset?

Thanks in advance!

**Comment by JakubSochor** [comment]
Temporarily, you can download dataset from this location. Password is BrnoCompSpeed.

**Comment by JakubSochor** [comment]
https://nextcloud.fit.vutbr.cz/s/NXWYSkSs2W2WgwH

**Comment by bongoramondo** [comment]
Hi, @JakubSochor 

I am uni and I wanted to use your low-resolution plate recognition dataset for one of my coursework's final projects. 
Unfortunately, the link [https://medusa.fit.vutbr.cz/traffic/](https://medusa.fit.vutbr.cz/traffic/) is inactive.
Is there any way to obtain the dataset?

**Comment by JakubSochor** [comment]
Can you please reach out to ispanhel@fit.vutbr.cz? He is handling the
dataset now.

**Comment by RubenEu** [comment]
I'm trying to download the dataset but the password 'BrnoCompSpeed' is wrong :(

I'm doing my final degree about speed measurement and I'm interesting in this dataset, thank you!

**Comment by yiwei-huangee** [comment]
hi, @JakubSochor .
I'm a student now doing the final project. The dataset is unavailable now, could you please activate it?
I'll be very appreciate.

**Comment by JeremyCKT** [comment]
> https://nextcloud.fit.vutbr.cz/s/NXWYSkSs2W2WgwH

Hello @JakubSochor 
The link needs password to access, could you give me the password??
I'm doing the research of speed measurement and I need the dataset, please.
Thanks!!

**Comment by Amrsaeed** [comment]
> Temporarily, you can download dataset from this location. Password is BrnoCompSpeed.

Hello,
This password is not currently working. Is there another one?

**Comment by zck921031** [comment]
> https://nextcloud.fit.vutbr.cz/s/NXWYSkSs2W2WgwH

Any update? Thank you in advance!

**Comment by zck921031** [comment]
> > https://nextcloud.fit.vutbr.cz/s/NXWYSkSs2W2WgwH
> 
> Any update? Thank you in advance!

Password is wrong.

**Comment by liyd** [comment]
Any update?

**Comment by hashshura** [comment]
Hi guys, just wanted to give infos from my side (not the author of this dataset).
I needed to redownload the database back then and cannot use said link:

> https://nextcloud.fit.vutbr.cz/s/NXWYSkSs2W2WgwH

so I went and personally contact ispanhel@fit.vutbr.cz, and he gave me another working temporary link.

Maybe you guys can try contact him too~

**Comment by JakubSochor** [comment]
I am no longer at academia; however, I updated the download instructions.

https://github.com/JakubSochor/BrnoCompSpeed#download
