### ISSUE TITLE
error in getting result

### ISSUE THREAD

**Issue by gentle1212** [JakubSochor/BrnoCompSpeed#13]
I am getting the following error. I think the result folder or a json file mentioned can resolve this problem. Anyone please provide me the results folder or a (system_dubska_bmvc14.json) file it will be very helpful for me. Thanks in advance 
![error](https://user-images.githubusercontent.com/63908294/121998082-c1953f80-cdc4-11eb-9a66-67216c250b23.png)

**Comment by JakubSochor** [comment]
I am no longer at academia; however, I updated the download instructions.

https://github.com/JakubSochor/BrnoCompSpeed#download
