### ISSUE TITLE
Failed to download data

### ISSUE THREAD

**Issue by dahliau** [JakubSochor/BrnoCompSpeed#16]
Hey, when I'm trying to download the data, I'm getting the following error:
`Failed to connect to medusa.fit.vutbr.cz port 443: Connection refused`

Is the data available somewhere else?
Tnx.

**Comment by jodumagpi** [comment]
it seems like a recurring issue. i hope they upload to mirror websites. @JakubSochor

**Comment by JakubSochor** [comment]
I am no longer at academia; however, I updated the download instructions.

https://github.com/JakubSochor/BrnoCompSpeed#download
