### ISSUE TITLE
Dataset is unavailable

### ISSUE THREAD

**Issue by Nuzhny007** [JakubSochor/BrnoCompSpeed#6]
Hello!
I'm working now on opensource project for Multitarget tracking: https://github.com/Smorodov/Multitarget-tracker
And one of direction of my interest - smart lights with automatic vehicles speed calculation. You can see example from youtube in Readme. And for this project I don't have a big dataset with vehicles. And your dataset now is unavailable. Do you can share it?
Thnx!

**Comment by JakubSochor** [comment]
Unfortunately, the server that is hosting the dataset is down for
maintenance. Hopefully, it will be back up next week.
