### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by ghost** [JakubSochor/BrnoCompSpeed#8]
Your website not running, I can't access to link?

**Comment by WangLiwen1994** [comment]
Face the same problem. I cannot access the dataset.

**Comment by JakubSochor** [comment]
+Jakub Špaňhel <ispanhel@fit.vutbr.cz> +Roman Juranek
<ijuranek@fit.vutbr.cz>
My colleagues are working on it. Hopefully, it will be live this week.
Jakub

**Comment by ghost** [comment]
Thank you so much!

**Comment by andrea-garritano** [comment]
Can you upload the dataset on Drive, Dropbox or other file hosting services?
Thank you!

**Comment by ghost** [comment]
This is not possible, because the dataset has a size is 200GB

**Comment by ghost** [comment]
Sorry, I have a project startup is "Estimation speed vehicle on a highway at Viet Nam", I need to find the member have a background about developer inference algorithm Deep Learning. with C/C++.

**Comment by JakubSochor** [comment]
Temporarily, you can download dataset from [this location](https://nextcloud.fit.vutbr.cz/s/NXWYSkSs2W2WgwH). Password is BrnoCompSpeed.
